# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: A Flock of Ducks
email: tw15egan@gmail.com
description: A website to showcase the diversity within IBM.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:3000" # the base hostname & protocol for your site
author: TJ Egan
twitter_username: tj_egan
github_username:  tw15egan

permalink: /:title.html
tags:

# Build settings
markdown: kramdown
